// tampermonkey/react/src/app.js
import React from 'react'
import './app.less'
import logo from '../public/icon.jpg'
export default class extends React.Component {
  constructor(props) {
    super(props)
    this.state = { show: true }
  }
  handleClose() {
    this.setState({
      show: !this.state.show,
    })
  }
  render() {
    let { show } = this.state
    return (
      <>
        {show ? (
          <div className="Wokoo">
            <header className="Wokoo-header">
              <img src={logo} className="Wokoo-logo" alt="logo" />
              <span
                className="Wokoo-close-icon"
                onClick={this.handleClose.bind(this)}
              >
                X
              </span>
              <p>
                欢迎使用 <a class="Wokoo-link" href="https://github.com/veeuidesign/veeui-react#readme">Vee UI</a>
              </p>
            </header>
          </div>
        ) : (
          <div className="Wokoo-hide" onClick={this.handleClose.bind(this)}>
            <img src={logo} className="Wokoo-hide-logo" alt="logo" />
            open
          </div>
        )}
      </>
    )
  }
}

// tampermonkey/vue/src/app.vue
<template>
  <div class="Wokoo" v-if="show">
    <header class="Wokoo-header">
      <img :src="logo" class="Wokoo-logo" alt="logo" />
      <span
        class="Wokoo-close-icon"
        @click="handleClose"
      >
        ×
      </span>
      <p>
        欢迎使用 <a class="Wokoo-link" href="https://github.com/veeuidesign/veeui-vue#readme">Vee UI</a>
      </p>
    </header>
  </div>
  <div class="Wokoo-hide" @click="handleClose" v-else>
    <img :src="logo" class="Wokoo-hide-logo" alt="logo" />
    open
  </div>
</template>
<script>
import './app.less'
import logo from '../public/icon.jpg'
export default {
  data: function() {
    return {
      logo,
      show: true
    }
  },
  methods: {
    handleClose() {
      this.show = !this.show
    }
  }
}
</script>
<style scoped>
</style>
